name: README STATS UPDATE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  schedule:
    # Runs at 12am IST
    - cron: '*/60 * * * *'
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "TRUE"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_PROJECTS: "TRUE"
          SHOW_PROFILE_VIEWS: "TRUE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_LOC_CHART: "FALSE"
